import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { extname, basename, join } from 'node:path';

const AUDIO_EXTENSIONS = ['.mp3', '.mp4', '.wav', '.m4a', '.ogg'];
const COVER_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp'];

const SONGS_DIR = 'public/media/songs';
const COVERS_DIR = 'public/media/song images';
const OUTPUT_FILE = 'src/data/songs.js';

// Paths relative to the public dir (no leading slash) — the generated file
// prefixes these with import.meta.env.BASE_URL at build time, so the site
// still finds its files whether it's hosted at the domain root or a GitHub
// Pages subpath (e.g. /some-repo/).
function relativeUrl(dir, filename) {
  return `${dir}/${encodeURIComponent(filename)}`;
}

function findCover(baseName) {
  if (!existsSync(COVERS_DIR)) return null;
  for (const ext of COVER_EXTENSIONS) {
    if (existsSync(join(COVERS_DIR, baseName + ext))) {
      return relativeUrl('media/song%20images', baseName + ext);
    }
  }
  return null;
}

function generateSongs() {
  const files = existsSync(SONGS_DIR)
    ? readdirSync(SONGS_DIR)
        .filter((file) => AUDIO_EXTENSIONS.includes(extname(file).toLowerCase()))
        .sort((a, b) => a.localeCompare(b))
    : [];

  const songs = files.map((file) => {
    const baseName = basename(file, extname(file));
    return {
      id: baseName,
      title: baseName,
      cover: findCover(baseName),
      src: relativeUrl('media/songs', file),
    };
  });

  const entries = songs
    .map((song) => {
      const cover = song.cover ? `BASE_URL + ${JSON.stringify(song.cover)}` : 'null';
      const src = `BASE_URL + ${JSON.stringify(song.src)}`;
      return `  { id: ${JSON.stringify(song.id)}, title: ${JSON.stringify(song.title)}, cover: ${cover}, src: ${src} }`;
    })
    .join(',\n');

  const contents = `// AUTO-GENERATED by vite-plugins/songs-plugin.mjs — do not edit by hand.
// Add or remove files in "public/media/songs" (audio) and
// "public/media/song images" (cover art, same filename) and this
// regenerates automatically — no code changes needed.
const BASE_URL = import.meta.env.BASE_URL;
const songs = [
${entries}
];

export default songs;
`;

  writeFileSync(OUTPUT_FILE, contents);
}

export function songsPlugin() {
  return {
    name: 'songs-plugin',
    buildStart() {
      generateSongs();
    },
    configureServer(server) {
      generateSongs();
      server.watcher.add([SONGS_DIR, COVERS_DIR]);
      server.watcher.on('add', (path) => {
        if (path.includes('media/songs') || path.includes('media/song images')) generateSongs();
      });
      server.watcher.on('unlink', (path) => {
        if (path.includes('media/songs') || path.includes('media/song images')) generateSongs();
      });
    },
  };
}
